### ISSUE TITLE
build ColorMorsePainting on Mac

### ISSUE THREAD

**Issue by MKesenheimer** [kallaballa/ColorMorsePainting#2]
I tried to build ColorMorsePainting on my Mac (model 2014, OSX 10.11, command line tools and gcc5 installed), but compilation failed with the following linker error:
[Error.txt](https://github.com/kallaballa/ColorMorsePainting/files/38734/Error.txt)

Since I installed boost with Macports in /opt/local/, I had to slightly modify the Makefile.
[Makefile.txt](https://github.com/kallaballa/ColorMorsePainting/files/38735/Makefile.txt)

So I think the compiler finds all the source files and the library, but the linker has some problems. What do you suggest?

**Comment by MKesenheimer** [comment]
Ah, now I was able to compile the code.

I uploaded the new Makefile so that anybody who has the same problem can use it.
[Makefile.txt](https://github.com/kallaballa/ColorMorsePainting/files/38749/Makefile.txt)
The problem was, that boost was compiled with clang++ and the flag stdc++11. I changed -std=c++0x to -std=c++11.

Maybe you can add the changes to your Makefile with a simple if-statement, which asks for the installed clang compiler version or for the stdc++ flag which was used to compile boost.

Btw: Very nice project!

**Comment by kallaballa** [comment]
thx! gonna fix it right away

**Comment by kallaballa** [comment]
i'm not sure i got it all right, so i created a new branch (macosx) https://github.com/kallaballa/ColorMorsePainting/tree/macosx

could you please check?

**Comment by nueh** [comment]
It compiles on Mac OS X 10.11 using the boost libraries from homebrew.

**Comment by MKesenheimer** [comment]
@kallaballa: I have no Mac OS computer available at the moment, but I can try again later. Thanks for fixing it.

**Comment by kallaballa** [comment]
thx!

**Comment by seclorum** [comment]
I can confirm it works great.
